Revert "Include `app` label in OpsLevel component (#58)" (#60)
This reverts commit f5beae9b73009dcbb44cfaacad1f03cd669e9c94. Mirror
Maker 2 fails to build under this change:

    $ kustomize build mirror-maker-2/flexible/
    Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/home/mjh/src/uw/kafka-manifests/shared/opslevel': copy operation does not apply: doc is missing destination path: /metadata/labels/app: missing value"